version: "3"

env:
  CLANG: /usr/bin/clang++
  DEBUG: -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON
  BUILD: -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF

tasks:
  default:
    - task: build-test
    - task: run-test

  build-test:
    cmds:
      - cmake -S . -B build -DCMAKE_CXX_COMPILER=${CLANG} ${DEBUG}
      - cmake --build build

  build:
    cmds:
      - cmake -S . -B build -DCMAKE_CXX_COMPILER=${CLANG} ${BUILD}
      - cmake --build build

  run-test:
    cmds:
      - ./build/tests/graph-test.out

  valgrind:
    cmds:
      - valgrind --leak-check=full --show-leak-kinds=all ./build/tests/graph-test.out

  gdb:
    cmds:
      - gdb ./build/tests/graph-test.out

  clean:
    cmds:
      - rm -rf build || true
